apiVersion: v1
kind: Secret
metadata:
  name: secret-dockerhub
  namespace: jenkins
data:
  config.json: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJoYW5qaTk2IiwicGFzc3dvcmQiOiJkY2tyX3BhdF9QZU90b1VwWDI3YUFETFY0RmUyUWh1blBmYkkiLCJlbWFpbCI6ImhhbnNlZTE5OTZAZ21haWwuY29tIiwiYXV0aCI6ImFHRnVhbWs1Tmpwa1kydHlYM0JoZEY5UVpVOTBiMVZ3V0RJM1lVRkVURlkwUm1VeVVXaDFibEJtWWtrPSJ9fX0=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets-properties
  namespace: jenkins
type: Opaque
data:
  jenkins.admin.user: YWRtaW4K
  jenkins.admin.password: YWRtaW4K
  github.credential.ssh: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUpMOFllNzJrRUdKSnhNa0l4QVIxNkdjcUk5S3JndGpVUU1Bd3ViZlJsWDggaGFuc2VlMTk5NkBnbWFpbC5jb20K
  github.credential.token: Z2hwX01rMWNsOVNyMmRUQUEyVENCVHFNeDRldHl4ZzlVaDFManNaRQo=
  sonar.credential.token: c3F1X2E1YzQ1NTBiODgyNWY2MzkxNzkwNmY2YWMyOWU2Yjk3MDBlNzRkOGQK