apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-master
  ports:
    - name: j-svc-httpport
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32500
    - name: jnlp-svc-httpport
      protocol: TCP
      port: 50000
      targetPort: 50000
    
