apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeoff-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: timeoff
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: timeoff
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - timeoff
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: app.kubernetes.io/name
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: timeoff
      containers:
        - name: timeoff-app
          image: hanji96/timeoff-app-dev:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "800m"
          imagePullPolicy: Always
          volumeMounts:
            - name: prueba
              mountPath: /home/prueba
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: "/login"
              port: 3000
            initialDelaySeconds: 10
            failureThreshold: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/login"
              port: 3000
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 3000
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: prueba
          emptyDir: {}